name: Tableconv CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.13
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: "3.13"
    - name: Install Python Dependencies
      run: |
        python -m pip install uv
        uv sync
    - name: Test
      run: |
        make test-ci


