name: Tableconv CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
        pip install -r requirements-dev.txt
    - name: Test
      run: |
        make test-ci


